# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_milstein <- function(x0, L, t, theta, drift_pntr, diffusion_pntr, ddiffusion_pntr, positive, seed) {
    .Call('_crashtest_R_milstein', PACKAGE = 'crashtest', x0, L, t, theta, drift_pntr, diffusion_pntr, ddiffusion_pntr, positive, seed)
}

